### ISSUE TITLE
Projections support

### ISSUE THREAD

**Issue by Rajivhost** [ameier38/equinox-tutorial#6]
Hi Andrew,
How about projections?

**Comment by bartelink** [comment]
A good question indeed. One thing to mention - Any projections-related stuff in the Equinox repo has been moved to https://github.com/jet/propulsion - happy to discuss in #equinox in the DDD-CQRS-ES slack (signup link on Equinox readme)

**Comment by andymeierdev** [comment]
@Rajivhost  Added projections in order to query across streams (i.e., get a list of all the leases that have been created).

- Creating projections https://github.com/ameier38/equinox-tutorial/blob/master/lease-api/src/Lease/Lease.Projection.fs
- Using `DepracatedRawName` to get the projected stream https://github.com/ameier38/equinox-tutorial/blob/master/lease-api/src/Lease/Lease.Service.fs#L116
- Leases projection https://github.com/ameier38/equinox-tutorial/blob/master/lease-api/src/Lease/projections/leases.js
